#!/bin/bash
# Daily Digest Generator - called by OpenClaw cron
# This script is a placeholder; the actual generation is done by OpenClaw's AI agent
set -e

REPO_DIR="/Users/flw/.openclaw/workspace/daily-digest"
DATE=$(date +%Y-%m-%d)
REPORT="$REPO_DIR/reports/$DATE.md"

if [ -f "$REPORT" ]; then
  echo "Report for $DATE already exists"
  exit 0
fi

echo "Report will be generated by OpenClaw agent for $DATE"
